### ISSUE TITLE
InvalidDateTime errors

### ISSUE THREAD

**Issue by wezm** [feed-rs/feed-rs#7]
I did some testing and found the following feeds caused an `InvalidDateTime` error of one sort or another:

```
thread 'main' panicked at 'unable to parse http://www.breakingthin.gs/rss.xml: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://donmelton.com/rss.xml: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.evanmiller.org/news.xml: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.sealiesoftware.com/blog/rss.xml: ParseError(InvalidDateTime(ParseError(OutOfRange)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://sourceforge.net/p/objectivelib/news/feed: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://feeds.feedburner.com/silverback: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://feeds.feedburner.com/simpledesktops: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://theredditblog.disqus.com/lesswrong_the_coolest_use_of_reddit_source_weve_found_to_date/latest.rss: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.xkcd.com/rss.xml: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.mechanicalgirl.com/feeds/all/: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://cdevroe.com/status/feed: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://feeds.feedburner.com/danielmall-articles: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://alex.amiran.it/rss.xml: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://feeds.feedburner.com/oshogbo: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://www.forrestthewoods.com/rss.xml: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://osblog.stephenmarz.com/feed.rss: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://myrrlyn.net/blog.rss: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://blog.burntsushi.net/index.xml: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://interrupt.memfault.com/blog/feed.xml: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://duncan.bayne.id.au/feed.xml: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://groups.google.com/forum/feed/pagedout-notifications/msgs/rss.xml?num=15: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://feeds.feedburner.com/simpledesktops: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://theredditblog.disqus.com/lesswrong_the_coolest_use_of_reddit_source_weve_found_to_date/latest.rss: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.breakingthin.gs/rss.xml: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.evanmiller.org/news.xml: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://feeds.feedburner.com/danielmall-articles: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://duncan.bayne.id.au/feed.xml: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://feeds.feedburner.com/oshogbo: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.xkcd.com/rss.xml: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.sealiesoftware.com/blog/rss.xml: ParseError(InvalidDateTime(ParseError(OutOfRange)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.shervinemami.info/rss.xml: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://donmelton.com/rss.xml: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://cdevroe.com/status/feed: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://sourceforge.net/p/objectivelib/news/feed: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://blog.burntsushi.net/index.xml: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://alex.amiran.it/rss.xml: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://myrrlyn.net/blog.rss: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://www.forrestthewoods.com/rss.xml: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse https://interrupt.memfault.com/blog/feed.xml: ParseError(InvalidDateTime(ParseError(Invalid)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://osblog.stephenmarz.com/feed.rss: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://feeds.feedburner.com/silverback: ParseError(InvalidDateTime(ParseError(Impossible)))', src/libcore/result.rs:1165:5
thread 'main' panicked at 'unable to parse http://www.mechanicalgirl.com/feeds/all/: ParseError(InvalidDateTime(ParseError(NotEnough)))', src/libcore/result.rs:1165:5
```

**Comment by markpritchard** [comment]
Thanks very much for the bug report @wezm - I suspected that the initial round of tests would highlight lots of issues (I strictly implemented the spec ... now to find and fix all the cases where real feeds differ).

Will grab some of these feeds and fix the problems.

**Comment by markpritchard** [comment]
There is a bunch of wacky data in these feeds - that was entertaining to fix. I don't have a fix for https://feeds.feedburner.com/oshogbo, it is using a really strange formate e.g.  "Dec. 9, 2019, 6:11 p.m."

Will have to do some research into that and work out if its something we want to parse.
